# Generated by Django 2.2.1 on 2019-05-09 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('timeOfConstruction', models.IntegerField()),
                ('timeOfRegistration', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField()),
                ('displayImage', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('startDate', models.DateField(blank=True, default=None, null=True)),
                ('endDate', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=30)),
                ('cardHolder', models.CharField(max_length=80)),
                ('expMonth', models.IntegerField()),
                ('expYear', models.IntegerField()),
                ('address', models.CharField(max_length=80)),
                ('aptSuite', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PriceLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesCost', models.CharField(max_length=20)),
                ('appraisalCost', models.CharField(max_length=15)),
                ('photoCost', models.CharField(max_length=15)),
                ('managementCost', models.CharField(max_length=15)),
                ('dataCollection', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('profileImagePath', models.CharField(default=None, max_length=50000)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('desc', models.TextField()),
                ('registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('soldOnDate', models.DateTimeField(default=None)),
                ('openHouse', models.CharField(default=None, max_length=75)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Users')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartments')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartments.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='listingDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.CharField(default=None, max_length=75)),
                ('description', models.CharField(default=None, max_length=50)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Listings')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Users'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Locations'),
        ),
        migrations.CreateModel(
            name='ApartmentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=5000)),
                ('aID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartments')),
            ],
        ),
    ]
