# Generated by Django 2.2.1 on 2019-05-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='timeOfConstruction',
        ),
    ]
