# Generated by Django 2.2.1 on 2019-05-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingdocs',
            name='attachment',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='listingdocs',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
