# Generated by Django 2.2.1 on 2019-05-10 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_apartments_timeofconstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='timeOfConstruction',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
