# Generated by Django 2.2.1 on 2019-05-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartments_timeofconstruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='price',
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='timeOfRegistration',
        ),
    ]
