# Generated by Django 2.2.1 on 2019-05-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20190510_0954'),
        ('apartments', '0002_auto_20190509_1457'),
    ]

    operations = [
    ]
