# Generated by Django 2.2.1 on 2019-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190510_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profileImagePath',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='workplace',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
